apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}:{{ .Values.nginx.tag }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: filebrowser-pvc
