{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.allowSameNamespace }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress
{{- end }}