{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.defaultDeny }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}