{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.egressRules }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limited-egress
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
spec:
  podSelector: {}
  egress:
  {{- range .Values.networkPolicies.egressRules }}
  - to:
    {{- range .toNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ .name }}
    {{- if .podLabels }}
      podSelector:
        matchLabels:
          {{- toYaml .podLabels | nindent 10 }}
    {{- end }}
    {{- end }}
    {{- if .ports }}
    ports:
    {{- range .ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
    {{- end }}
    {{- end }}
  {{- end }}
  policyTypes:
  - Egress
{{- end }}