apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-users
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "naas.labels" . | nindent 4 }}
subjects:
{{- range .Values.rbac.userGroups }}
- kind: {{ .kind }}
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
roleRef:
  kind: Role
  name: namespace-user
  apiGroup: rbac.authorization.k8s.io