{{- range .Values.rbac.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "naas.labels" $ | nindent 4 }}
---
{{- if .createRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-access
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "naas.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .name }}
  namespace: {{ $.Values.namespace.name }}
roleRef:
  kind: Role
  name: namespace-user
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}