apiVersion: v1
kind: Namespace
metadata:
  name: finance-dev
  labels:
    team: finance
    environment: dev
    managed-by: platform-team

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: finance-dev-quota
  namespace: finance-dev
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "32Gi"
    limits.cpu: "15"
    limits.memory: "48Gi"
    pods: "50"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: finance-dev-limits
  namespace: finance-dev
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
    type: Container