apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    team: {{ .Values.namespace }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace }}-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
#    requests.cpu: "4"
#    requests.memory: "2Gi"
    limits.cpu: {{ .Values.quota.cpu }}
    limits.memory: {{ .Values.quota.memory }}
    pods: {{ .Values.quota.pods }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
    type: Container